### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by k-304** [SnipeLike/WinBackupper#10]
Hi T0m

I just went to test all new amazing features but I wasn't able to start the programm.
Here a Screenshot:
![error 10](https://cloud.githubusercontent.com/assets/8758440/7845653/8a67c4b4-04b8-11e5-9388-caa7cf14557a.PNG)

Can you please take a look at it or is my version not the newest...? (It should because I Synced all new staff...)

**Comment by MrCryptoT** [comment]
Please do the following: 
1)Within Github for Windows (Apllication) rightclick your Repository and click on "Open in Git Shell" 
2) enter (without quotes) :"
git status
"
3)tell me what the output of the git console is.... 
also please:
1)Enter the command described in the following article and tell me what kind of output there is...
It should return a list of "Conflicted" files... (My output is "nothing" - not as a string - jsut nothing happens, there is no output at all on my side within my Repository)
http://stackoverflow.com/questions/3065650/whats-the-simplest-way-to-git-a-list-of-conflicted-files
1.b) If there are any Files within the output, please check them with a text editor and search for the "<<<<<" part marking an conflict area within a file - according to this article : https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/
(Wihtin the ARticle is also a way how to store the command as an alias or executable file - so if the comand works we don thave to type it each time!)

This should help me to further understand this Issue and resolve it. (For now I actually "denied" my pull request) Hope we can resolve this soon. (Regarding the Build error, please  
download [Current Version of my Fork here](http://thcode.ddns.net/temp20150528.7z) so you can review the changes for now and check if it builds correctly... If you want you can just create a temp folder and copy it in there until the PR Issue is solved...
Have a good one - working on it =) )

**Comment by k-304** [comment]
Please Push your newest Code to Git, because I found someting to overwrite my local files and I will to this as soon as you pushed the newest Code. :D

**Comment by k-304** [comment]
Ps. No conflicted files....
![error 10_p1](https://cloud.githubusercontent.com/assets/8758440/7866652/343e7db2-0571-11e5-91f5-5d8458bb1a1a.PNG)

**Comment by MrCryptoT** [comment]
Well my fork is synced with my current code.I guess i missunderstood what you originally meant... when overwriting your files, make sure to not overwrite .git files etc... also make a backup ☺.well then - hear from you if the overwriting works. 

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: SnipeLike notifications@github.com 
Datum: 28.05.2015  19:39  (GMT+01:00) 
An: SnipeLike/WinBackupper WinBackupper@noreply.github.com 
Cc: Tom tom.harrison@hotmail.ch 
Betreff: Re: [WinBackupper] Build Error  (#10) 

Ps. No conflicted files....

**Comment by k-304** [comment]
Of course I created a backup ;)
Is it possible that the Sync failed...? Last change is "one day ago"...
Can you create a Pull-Request?

**Comment by MrCryptoT** [comment]
Finaly I should have managed to find my errors and correct them. I directly corrected the errors in your repo and reforked it. now everything should work again. (including the actual backup function) 
Please close this Issue if you can confirm this. Have a good one mate! Im so sorry for the trouble.

**Comment by k-304** [comment]
There is still a small bug...
Run the programm and go to the settings form. Create a new entry and save it. Close all forms and let the programm build again and then I got an error:
![0 0 0 6_bug 1](https://cloud.githubusercontent.com/assets/8758440/7901192/255c587a-077c-11e5-9bcf-72d14e2c5307.PNG)

**Comment by k-304** [comment]
It works!
