### ISSUE TITLE
Backup old Default.xml File before saving changes

### ISSUE THREAD

**Issue by MrCryptoT** [SnipeLike/WinBackupper#15]
What do you think about backing up the old default XML file before saving changes in the config? 
Let s say like the last 30 xml files?

Just a thought thoutgh...

**Comment by k-304** [comment]
Like I said you today... I think it is not necessary.

**Comment by MrCryptoT** [comment]
Allright - you're right - reconfiguring everthing shouldn't be an issue.
Also, someone could just copy paste the XML itself to "backup" the config.
