### ISSUE TITLE
Documentation of Software

### ISSUE THREAD

**Issue by MrCryptoT** [SnipeLike/WinBackupper#19]
Hey Snipe - short question here... 
Well acutally 3:
1)Where should i write down internal documentation for the Software (like code explanations, "workflows" etc...)? 
I think it would be cool if thats publicly available... Since the code is opensource it would make it much easier for others to use it.
2) Where to write the "How To"-part of the documentation? Should we use an external Website or Github itself? (I'd prefer Github - it would be centralized)
2a) Where to release Releases? Where to ohst the actual executable files? (Same things as 2) - externaly or github? )

**Comment by k-304** [comment]
Hey T0m
1) Would it make sense to create a new .txt or .md (like README.md) to write down everything there?
2) I'd prefer to write it in our README.md, because this file is always shown on the bottom by visiting our project. Like I did it in my TemPS3 Repo.
2a) I would offer my server for that.
(Do you mean for people who want to start using our amazing tool?)
Go to http://xcvi.ch/project/winbackupper.html

Or my TemPS3 example: http://xcvi.ch/project/temps3.html

**Comment by MrCryptoT** [comment]
Will awnser in detail over the WE 2a)why not using githubs "release" function?
Have a good one - need to chill out first before i start looking at code again ^^
Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: SnipeLike notifications@github.com 
Datum: 11.06.2015  22:13  (GMT+01:00) 
An: SnipeLike/WinBackupper WinBackupper@noreply.github.com 
Cc: Tom tom.harrison@hotmail.ch 
Betreff: Re: [WinBackupper] Documentation of Software (#19) 

Hey T0m

1) Would it make sense to create a new .txt or .md (like README.md) to write down everything there?

2) I'd prefer to write it in our README.md, because this file is always shown on the bottom by visiting our project. Like I did it in my TemPS3 Repo.

2a) I would offer my server for that.

(Do you mean for people who want to start using our amazing tool?)

Go to http://xcvi.ch/project/winbackupper/

**Comment by k-304** [comment]
I dont know this github function... maybe we can use it.
Have a great WE!

**Comment by MrCryptoT** [comment]
Simply have a look here => https://github.com/SnipeLike/WinBackupper/releases
There you could upload an exe File (I guess a self-extracting-archive would do the job) or other files (not sure how much/which filetypes) so that others can see the release directly on github. 
Thanks you too mate

EDIT: And regarding the Documentation it certainly would. 
I guess it's better than the Wiki feature - I guess the wiki may look nicer, but the Wiki is another click away and therefore might be overseen.

**Comment by MrCryptoT** [comment]
Just a Quick reivision. 
1) Dev Documentation workflow.md
2)Documentation for Users is within the Readme.md
3) Releases - Release feature of Github.
I'll keep this one open - but Lock it. everything's clear =)

**Comment by MrCryptoT** [comment]
Do you know a way to include images within an md file? 
Cause otherwise I think we should realize it differntly. 
A "User manual" without Screenshots isn't the same =). 
I'll happily do that of course... but I'll wait until we disscussed where to put it. (and until we have the restore thing done)

**Comment by k-304** [comment]
http://stackoverflow.com/questions/14494747/add-images-to-readme-md-on-github

I found this one... here. Looks like it should work.
