### ISSUE TITLE
Timetable crash on saveing

### ISSUE THREAD

**Issue by k-304** [SnipeLike/WinBackupper#35]
Timetable Form crashes wehen I press on "Save & Exit"
So please have a look.

**Comment by MrCryptoT** [comment]
Should be fixxed by my last commit.

**Comment by k-304** [comment]
Oh realy...?
Hm...  it just crashed today in i think i got the  newest stuff.

Tom notifications@github.com schrieb am Mo., 27. Juli 2015 17:28:

**Comment by MrCryptoT** [comment]
On my Side it seems fixxed... 
It was an Issue with the "Nothing configured" string added...
The "Substring" checking if it's "nothing" was "asking" =>
"What are the chars from char 0 to 6"... but there is no 6th character in "20:00" there are only 5. 
Therefore an "Argumentoutofrange" exception occurs... 
I fixxed it by only asking for the first 5 "nothi"... 
(Just as an explanation =) )

**Comment by k-304** [comment]
Fixxed!
