### ISSUE TITLE
xmlReader.Load crash

### ISSUE THREAD

**Issue by k-304** [SnipeLike/WinBackupper#45]
Hi Tom

I found the following bug:
![image](https://cloud.githubusercontent.com/assets/8758440/9527871/e170fd30-4cf1-11e5-8299-189793eef268.png)

So how to get this error:
- Close VStudio
- Rename your "Debug" Folder to "DebugOLD" (or anything else)
- Open VS and start the programm
- Add Backupfolders etc.
- Hit the "Start Backup" Button from "home.vb"
- Enter "Full" - Backup and it should crash, because there is no "RestoreOverview.xml" File

I saw that there is a part of "if file exist" but this part is called after the loader:
![image](https://cloud.githubusercontent.com/assets/8758440/9528014/c5ebc882-4cf2-11e5-9660-46c42c3bfa85.png)

I did not tryed to fix that bug yet. Maybe we have luck and just need to replace the loader, so "may the force be with us"

**Comment by MrCryptoT** [comment]
Well I guess I moved it to the wrong position. Will quickly fix it afterwards.

Sent from my Samsung phone whilst fixing router problems in my server room which is on fire right now. So please forgive me any short anwsers or mistakes within them.

On Thu, Aug 27, 2015 at 10:35 AM -0700, "Ken" notifications@github.com wrote:
Assigned #45 to @T0mH4rr1s0n.

---

Reply to this email directly or view it on GitHub:
https://github.com/SnipeLike/WinBackupper/issues/45#event-394270939

**Comment by k-304** [comment]
Seems also fixxed from here.

**Comment by MrCryptoT** [comment]
Nice. Another aidsue fixxed =)
Am 29.08.2015 15:31 schrieb Ken notifications@github.com:Seems also fixxed from here.
