### ISSUE TITLE
rsync --link-dest="xy"

### ISSUE THREAD

**Issue by k-304** [SnipeLike/WinBackupper#50]
How about a link-dest function for our backups.... I know there is a diff/inc feature but this may be interesting...

**Comment by MrCryptoT** [comment]
Mhm... 
I realize we just had a lesson in school about rsync on linux... 
Not sure if such an Option is availlable in robocopy though. 
We can look into Sym Links if you want i think something like that i spossible. 
Will need some time though. 
Want ot test the SW as it is in the current state before investing time in new features.

**Comment by MrCryptoT** [comment]
If it's allright I'd love to Close this Issue. 
You know the reason - Robocopy Limitation. 
(Maybe something with hard/symlinks is possible, but im not Aware of it currently and don't really want to rewrite the backuproutine right now.. maybe something for the future?)
