### ISSUE TITLE
Back up will only backup files of Subdir - not the Sourcedir itself!

### ISSUE THREAD

**Issue by MrCryptoT** [SnipeLike/WinBackupper#8]
This is a Heavy bug - and I'm not yet sure how to fix it. 
In the "BackupDirectory" Function -  The Loop thorugh all files begins in all Subdirectories of the Sourcedir - but lleaves out the Sourcedir itself. 
And ugly fix is to repeat the for each filep!ath loop for the sourcedir too... 
See:
![image](https://cloud.githubusercontent.com/assets/8693733/7784550/1ada91fe-016a-11e5-8907-9797c8996baa.png)
![image](https://cloud.githubusercontent.com/assets/8693733/7784570/c7ec8fbe-016a-11e5-9839-3fb45361f43a.png)

If you have an Idea how to fix it properly I would be thankfull as hell. In the meantime I'll try to fix the Issues i've created. Have a good one!

**Comment by k-304** [comment]
First off...  damn u are fast in coding... xD

So if I understood this bug corectly maybe I found a less good sulution.
I'll tell it to you in school next week.

Tom notifications@github.com schrieb am Sa., 23. Mai 2015 16:44:

**Comment by MrCryptoT** [comment]
Should be fixxed in next pull request - was a copy&paste error!

**Comment by MrCryptoT** [comment]
@SnipeLike Could you please test this sometimes? It looks ok on my Side since the last Merge (#9).
When I tested, it seemed to have copied the file in the root source dir - but they are not yet copying it into a "%Date-Time%"-Folder... If it's okay on your Side too feel free to close the issue.
See you next week.

**Comment by MrCryptoT** [comment]
While correcting errors I also updated the cuntion to copy it into a Folder with the Date and time.
SHould work as far as i tested - the same with this Issue. Please close it as soon you can confirm it.

**Comment by k-304** [comment]
Confirmed!
